[WIP]: Feat/arclayer use deckgl wrapper
FixMyBerlin/fixmy.frontend pull request #710
Opened 2020-12-08 14:47 UTC by s-pic

## Context

Closes #568

## Description

* augments our reports overviewmap so that the linkages of hovered/selected reports/plannings to related plannings/reports is visualized using [Deck.gl ArcLayers](https://deck.gl/docs/api-reference/layers/arc-layer).
* wraps our Reports BaseMap in a [`deck.gl/Deck` ](https://deck.gl/docs/api-reference/core/deck) instance so that a tooltip is shown when an Arc item is hovered. The synchronization of deck.gl and our mapbox-map is done "by hand", by reacting to map moves and aplying the new view state to the deck.gl map. The synchronization would be a lot easier if we'd juse [react-mapbox-gl](https://www.npmjs.com/package/react-mapbox-gl)
* refactors the BaseMap component to use TypeScript and Hooks

## Screenshots
![arc_hover](https://user-images.githubusercontent.com/12786207/101497512-5b3de900-396b-11eb-9c68-e8a2dbc9eb07.gif)

# How can I test this?
* set `REGION=aachen` in .env, run dev server
* open http://localhost:8080/meldungen/karte/46. Linkages should be visualized
* hover other markers in the map, inspect their linkages

## Open aspects
As discussed, I won't much time to polish this within the next weeks. TBD:

* thorough review. E.g. I adapted some annoying eslint-rules, which is subject to discussion
* handshake with UX: does the look and behaviour meet our needs?
* automated tests
* merge conflicts
* newer bug (after I pulled in latest changes of /develop): If the foldout opens (when a report/planning is inspected or loaded via deep link), the map gets moved but the deck.gl wrapper does not get notified of the movement
* animated arcs? I had success by utilizing [react-spring](https://www.react-spring.io/) and a custom BrushingLayert [`BrushingLayer`](https://github.com/visgl/deck.gl/issues/2531#issuecomment-450475596)
* Type-Safety for Report Items.

2021-01-13 16:04 UTC, cafca requested changes
see comments

2021-01-13 16:04 UTC, cafca commented on tsconfig.json
> +      "es2019",
Maybe we can instead extend a tsconfig template for our ES version

2021-01-21 16:06 UTC, cafca approved these changes

2021-01-21 16:06 UTC, merged

2021-01-21 20:48 UTC, s-pic commented
Good job @cafca 🎉